default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= Rails.application.credentials.db[:db_name] %>
  username: <%= Rails.application.credentials.db[:usr] %>
  password: <%= Rails.application.credentials.db[:pwd] %>
  socket: <%= Rails.application.credentials.db[:socket] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default